### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by jonnyvaughan** [stevegal/solis_control#4]
Hi,

I'm having a tough time getting this working - both the inverter list function and the login function aren't working. 

When the login function is called, I get the following API response: 
{'success': False, 'code': 'Z0001', 'msg': 'Login has expired. Please login again', 'data': None}

The inverter function returns a 403 forbidden response.

I've double checked my login details and API credentials - I've tried using my email address and username for the login but neither work with the API calls. They work on soliscloud.com so I'm a bit stumped.

I checked with Solis - the API is enabled (and I'm using https://github.com/hultenvp/solis-sensor fine) on my account. I asked for the v2 API docs but they didn't respond to that request.

I wondered if it was a date/time issue but the time and timezone are correct on HA.

Any ideas?

Jonny

**Comment by jonnyvaughan** [comment]
I managed to get this working - I think it was the way the config values are set as either strings or not. Using configuration.yaml to store the values, this worked for me:

```
pyscript:
  apps:
    solis_control:
      config:
        secret: xxxxxxxxxxxxxxxxxxxxxxx
        key_id: "1234567890123"
        username: EMAIL_ADDRESS
        password: XXXXXXX
        plantId: "1234567890123"
```
